/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDraftsRouteImport } from './routes/admin/drafts'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'
import { Route as AdminPublishedRouteImport } from './routes/admin/published'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as UpdatesSlugRouteImport } from './routes/updates/$slug'
import { Route as AdminUpdatesIndexRouteImport } from './routes/admin/updates/index'
import { Route as AdminUpdatesNewRouteImport } from './routes/admin/updates/new'
import { Route as AdminUpdatesIdEditRouteImport } from './routes/admin/updates/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDraftsRoute = AdminDraftsRouteImport.update({
  id: '/admin/drafts',
  path: '/admin/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/admin/insights',
  path: '/admin/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublishedRoute = AdminPublishedRouteImport.update({
  id: '/admin/published',
  path: '/admin/published',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesIndexRoute = AdminUpdatesIndexRouteImport.update({
  id: '/admin/updates/',
  path: '/admin/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesNewRoute = AdminUpdatesNewRouteImport.update({
  id: '/admin/updates/new',
  path: '/admin/updates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesIdEditRoute = AdminUpdatesIdEditRouteImport.update({
  id: '/admin/updates/$id/edit',
  path: '/admin/updates/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/admin/updates/new': typeof AdminUpdatesNewRoute
  '/admin/updates/': typeof AdminUpdatesIndexRoute
  '/admin/updates/$id/edit': typeof AdminUpdatesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/admin/updates/new': typeof AdminUpdatesNewRoute
  '/admin/updates': typeof AdminUpdatesIndexRoute
  '/admin/updates/$id/edit': typeof AdminUpdatesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/admin/updates/new': typeof AdminUpdatesNewRoute
  '/admin/updates/': typeof AdminUpdatesIndexRoute
  '/admin/updates/$id/edit': typeof AdminUpdatesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/drafts'
    | '/admin/insights'
    | '/admin/published'
    | '/admin/settings'
    | '/updates/$slug'
    | '/admin/'
    | '/updates/'
    | '/admin/updates/new'
    | '/admin/updates/'
    | '/admin/updates/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/drafts'
    | '/admin/insights'
    | '/admin/published'
    | '/admin/settings'
    | '/updates/$slug'
    | '/admin'
    | '/updates'
    | '/admin/updates/new'
    | '/admin/updates'
    | '/admin/updates/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/drafts'
    | '/admin/insights'
    | '/admin/published'
    | '/admin/settings'
    | '/updates/$slug'
    | '/admin/'
    | '/updates/'
    | '/admin/updates/new'
    | '/admin/updates/'
    | '/admin/updates/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminDraftsRoute: typeof AdminDraftsRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminPublishedRoute: typeof AdminPublishedRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  AdminUpdatesNewRoute: typeof AdminUpdatesNewRoute
  AdminUpdatesIndexRoute: typeof AdminUpdatesIndexRoute
  AdminUpdatesIdEditRoute: typeof AdminUpdatesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drafts': {
      id: '/admin/drafts'
      path: '/admin/drafts'
      fullPath: '/admin/drafts'
      preLoaderRoute: typeof AdminDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/admin/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/published': {
      id: '/admin/published'
      path: '/admin/published'
      fullPath: '/admin/published'
      preLoaderRoute: typeof AdminPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates/': {
      id: '/admin/updates/'
      path: '/admin/updates'
      fullPath: '/admin/updates/'
      preLoaderRoute: typeof AdminUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates/new': {
      id: '/admin/updates/new'
      path: '/admin/updates/new'
      fullPath: '/admin/updates/new'
      preLoaderRoute: typeof AdminUpdatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates/$id/edit': {
      id: '/admin/updates/$id/edit'
      path: '/admin/updates/$id/edit'
      fullPath: '/admin/updates/$id/edit'
      preLoaderRoute: typeof AdminUpdatesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminDraftsRoute: AdminDraftsRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminPublishedRoute: AdminPublishedRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  AdminUpdatesNewRoute: AdminUpdatesNewRoute,
  AdminUpdatesIndexRoute: AdminUpdatesIndexRoute,
  AdminUpdatesIdEditRoute: AdminUpdatesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

